defmodule ESI.API do

  @version "0.4.1.dev1"

  def version, do: @version

  @type result :: ESI.API.Alliance.names_result
                | ESI.API.Alliance.corporations_result
                | ESI.API.Alliance.icons_result
                | ESI.API.Alliance.alliance_result
                | ESI.API.Alliance.alliances_result
                | ESI.API.Character.bookmarks_result
                | ESI.API.Character.fittings_result
                | ESI.API.Character.create_fittings_result
                | ESI.API.Character.ship_result
                | ESI.API.Character.search_result
                | ESI.API.Character.names_result
                | ESI.API.Character.delete_mail_label_result
                | ESI.API.Character.bookmark_folders_result
                | ESI.API.Character.assets_result
                | ESI.API.Character.skillqueue_result
                | ESI.API.Character.character_result
                | ESI.API.Character.planets_result
                | ESI.API.Character.create_cspa_result
                | ESI.API.Character.delete_contacts_result
                | ESI.API.Character.contacts_result
                | ESI.API.Character.create_contacts_result
                | ESI.API.Character.update_contacts_result
                | ESI.API.Character.clones_result
                | ESI.API.Character.mail_lists_result
                | ESI.API.Character.contact_labels_result
                | ESI.API.Character.skills_result
                | ESI.API.Character.killmail_recent_result
                | ESI.API.Character.calendar_result
                | ESI.API.Character.planet_result
                | ESI.API.Character.portrait_result
                | ESI.API.Character.mail_result
                | ESI.API.Character.create_mail_result
                | ESI.API.Character.delete_fitting_result
                | ESI.API.Character.calendar_event_result
                | ESI.API.Character.update_calendar_event_result
                | ESI.API.Character.wallets_result
                | ESI.API.Character.corporation_history_result
                | ESI.API.Character.location_result
                | ESI.API.Character.mail_labels_result
                | ESI.API.Character.create_mail_labels_result
                | ESI.API.Character.delete_mail_item_result
                | ESI.API.Character.mail_item_result
                | ESI.API.Character.update_mail_item_result
                | ESI.API.Corporation.alliance_history_result
                | ESI.API.Corporation.corporation_result
                | ESI.API.Corporation.members_result
                | ESI.API.Corporation.roles_result
                | ESI.API.Corporation.names_result
                | ESI.API.Corporation.structures_result
                | ESI.API.Corporation.icons_result
                | ESI.API.Corporation.npccorps_result
                | ESI.API.Fleet.members_result
                | ESI.API.Fleet.create_members_result
                | ESI.API.Fleet.delete_squad_result
                | ESI.API.Fleet.update_squad_result
                | ESI.API.Fleet.create_squads_result
                | ESI.API.Fleet.fleet_result
                | ESI.API.Fleet.update_fleet_result
                | ESI.API.Fleet.delete_member_result
                | ESI.API.Fleet.update_member_result
                | ESI.API.Fleet.wings_result
                | ESI.API.Fleet.create_wings_result
                | ESI.API.Fleet.delete_wing_result
                | ESI.API.Fleet.update_wing_result
                | ESI.API.Incursion.incursions_result
                | ESI.API.Industry.facilities_result
                | ESI.API.Industry.systems_result
                | ESI.API.Insurance.prices_result
                | ESI.API.Killmail.killmail_result
                | ESI.API.Market.orders_result
                | ESI.API.Market.prices_result
                | ESI.API.Market.structure_result
                | ESI.API.Market.history_result
                | ESI.API.Search.search_result
                | ESI.API.Sovereignty.campaigns_result
                | ESI.API.Sovereignty.structures_result
                | ESI.API.UI.open_information_window_result
                | ESI.API.UI.open_market_details_window_result
                | ESI.API.UI.open_new_mail_window_result
                | ESI.API.UI.set_autopilot_waypoint_result
                | ESI.API.UI.open_contract_window_result
                | ESI.API.Universe.structure_result
                | ESI.API.Universe.bloodlines_result
                | ESI.API.Universe.schematic_result
                | ESI.API.Universe.category_result
                | ESI.API.Universe.structures_result
                | ESI.API.Universe.groups_result
                | ESI.API.Universe.races_result
                | ESI.API.Universe.moon_result
                | ESI.API.Universe.constellation_result
                | ESI.API.Universe.categories_result
                | ESI.API.Universe.type_result
                | ESI.API.Universe.systems_result
                | ESI.API.Universe.constellations_result
                | ESI.API.Universe.system_result
                | ESI.API.Universe.group_result
                | ESI.API.Universe.factions_result
                | ESI.API.Universe.stargate_result
                | ESI.API.Universe.types_result
                | ESI.API.Universe.region_result
                | ESI.API.Universe.regions_result
                | ESI.API.Universe.planet_result
                | ESI.API.Universe.station_result
                | ESI.API.Universe.create_names_result
                | ESI.API.War.wars_result
                | ESI.API.War.killmails_result
                | ESI.API.War.war_result

end